apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: tech-challenge-i
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-i
  template:
    metadata:
      labels:
        app: tech-challenge-i
    spec:
      containers:
        - name: api-container
          image: larissay/tech-challenge-i:latest 
          ports:
            - containerPort: 8080  
          env:
            - name: DATABASE_URL  # Defina variáveis de ambiente, se necessário
              value: "jdbc:postgresql://db-service:5432/db0001"

