apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-api-service
spec:
  type: LoadBalancer  # Pode ser ClusterIP, NodePort ou LoadBalancer dependendo da necessidade
  selector:
    app: tech-challenge-i  # Seleciona os pods com o label "app: my-api"
  ports:
    - protocol: TCP
      port: 80  # Porta exposta no serviço
      targetPort: 30900  # Porta do container (onde a API está escutando)
  