services:
  app:
    container_name: api-container
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://db:5432/db0001
    networks:
      - mynetwork

  db:
    image: postgres:13
    container_name: db-container
    environment:
      - POSTGRES_USER=postegre
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=db0001
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata:  # Declarando o volume pgdata
    driver: local